[mongodb]
mongodb.venaws.in
[catalogue]
catalogue.venaws.in
[redis]
redis.venaws.in
[user]
user.venaws.in
[cart]
cart.venaws.in
[frontend]
frontend.venaws.in
[mysql]
mysql.venaws.in
[shipping]
shipping.venaws.in
[rabbitmq]
rabbitmq.venaws.in
[payment]
payment.venaws.in

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321


[localhost]
localhost